[package]
name = "mcsl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
craftping = "0.3.0"
ctrlc = "3.2.2"
enquote = "1.1.0"
#lazy_static = "1.4.0"
#mojang-api = "0.6.1"